version: '3.1'
services:
  database:
    image: "postgres"
    restart: always
    environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
        POSTGRES_DB: testdb
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
volumes:
  database-data: