version: '3.1'
services:
  database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    ports:
      - 5455:5432
volumes:
  database-data: